RUNS   := results/runs.csv
FIGDIR := figures

.PHONY: selftest check-arms deliver table1 table2 figures figures-published report thesis slides all clean-figures clean-thesis clean-slides

# The reporting chain, verified against a fixture with known answers. Needs no
# GPU, so it runs on the dev machine as well as inside the Kaggle kernel.
selftest:
	python tools/selftest_pipeline.py
	python tools/test_instruments.py
	python tools/test_kaggle_accounts.py

# The arms are tags, so they cannot drift. This checks they are all still
# there and prints what arm B introduces over arm A, which is the whole of
# the difference between the two columns every comparison rests on.
check-arms:
	@for r in arm-mip-splatting arm-3dgs-baseline arm-3dgs-vanilla probe-pre-gof probe-c1-rasteriser; do \
		git rev-parse -q --verify "$$r^{commit}" >/dev/null \
			|| { echo "MISSING ref: $$r"; exit 1; }; \
		printf "  %-22s %s\n" "$$r" "$$(git rev-parse --short $$r)"; \
	done
	@echo "--- arm B over arm A (expect 4 files, 7 insertions, 1 deletion) ---"
	@git diff arm-mip-splatting...arm-3dgs-baseline --stat | tail -1

# ITERS selects which runs to average: 30000 is the R1/R2 target, 7000 the R0
# smoke rows. Mixing them would produce a number describing neither run.
ITERS  ?= 30000

table1:
	python tools/make_table.py --table 1 --runs $(RUNS) --iterations $(ITERS) --md results/table1.md

table2:
	python tools/make_table.py --table 2 --runs $(RUNS) --iterations $(ITERS) --md results/table2.md

figures:
	python tools/make_figures.py --mode measured --runs $(RUNS) --iterations $(ITERS) --out $(FIGDIR)

# The §13 report for one rung, rendered from the summary.json its kernel wrote.
#   make report SUMMARY=results/kaggle_runs/r0_smoke_v3/summary.json OUT=results/R0-report.md
SUMMARY ?= results/kaggle_runs/r0_smoke_v3/summary.json
OUT     ?= results/R0-report.md

report:
	python tools/report_rung.py $(SUMMARY) --md $(OUT)


# The thesis. Regenerates every measured table and every inline number from
# results/runs.csv first, so the document's claim that no number in it is typed
# by hand is enforced by the build rather than asserted in the text.
# Three passes: labels, then references, then the table of contents.
thesis:
	python tools/make_tex.py --runs $(RUNS) --out thesis/generated
	# MEASURED, not published. Figure 1's caption promises "this project's own
	# reproduction overlaid where measured", and for a long time this line said
	# --mode published, so the overlay the caption described was not in the
	# figure. It also meant the measured figures -- 7 through 10, the ones that
	# carry results -- were never regenerated by a thesis build at all, and
	# make_figures' own exit code was never on the critical path: it had been
	# failing on the b1-fisher slug for weeks without turning the build red.
	python tools/make_figures.py --mode measured --runs $(RUNS) 	    --iterations $(ITERS) --out thesis/figures
	# The qualitative panels, from the renders each rung kept. Skipped with a
	# message rather than failing if results/renders is empty, since a fresh
	# clone has no pictures until tools/fetch_renders.py has run.
	python tools/make_qualitative.py --out thesis/figures
	# The explanatory diagrams: concepts, not measurements. They depend on
	# nothing but the palette, so they are cheap and always regenerated.
	python tools/make_diagrams.py --out thesis/figures
	cd thesis && pdflatex -interaction=nonstopmode main.tex >/dev/null
	cd thesis && pdflatex -interaction=nonstopmode main.tex >/dev/null
	cd thesis && pdflatex -interaction=nonstopmode main.tex | grep -E "^!|Reference .* undefined" || true
	@echo "--> thesis/main.pdf"

# The panel deck. Reads the same three sources make_tex.py does -- runs.csv, the
# rung summaries and thesis/generated/measured.tex -- and re-renders the figures
# as PNG, because PowerPoint embeds neither PDF nor SVG. A slide therefore
# cannot disagree with the thesis about a number.
slides:
	python tools/make_slides.py --runs $(RUNS) --out slides
	@echo "--> slides/BTP-Panel.pptx"

# Everything a submission needs, from one CSV.
all: thesis slides

# The files the panel is handed, under the names it expects. They are
# committed, so what was submitted stays recoverable at the tag that
# submitted it. The PDF export of the deck needs PowerPoint and is the one
# step this cannot do.
DELIVER ?= submission

deliver: all
	cp thesis/main.pdf $(DELIVER)/BTP-Thesis.pdf
	cp slides/BTP-Panel.pptx $(DELIVER)/BTP-Panel-Presentation.pptx
	@echo "--> $(DELIVER)/BTP-Thesis.pdf and $(DELIVER)/BTP-Panel-Presentation.pptx"
	@echo "    re-export $(DELIVER)/BTP-Panel-Presentation.pdf from the .pptx"

clean-slides:
	rm -rf slides

clean-thesis:
	rm -f thesis/*.aux thesis/*.log thesis/*.out thesis/*.toc thesis/main.pdf

# Target-only reference figures (published numbers, never our measurements).
# Kept separate so `make figures` can never be satisfied by them.
figures-published:
	python tools/make_figures.py --mode published --out $(FIGDIR)/published

clean-figures:
	rm -rf $(FIGDIR)
